
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SalutThomasWSService", targetNamespace = "http://simple.demows.thomas.com/", wsdlLocation = "http://localhost:8888/salut?wsdl")
public class SalutThomasWSService
    extends Service
{

    private final static URL SALUTTHOMASWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SALUTTHOMASWSSERVICE_EXCEPTION;
    private final static QName SALUTTHOMASWSSERVICE_QNAME = new QName("http://simple.demows.thomas.com/", "SalutThomasWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/salut?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SALUTTHOMASWSSERVICE_WSDL_LOCATION = url;
        SALUTTHOMASWSSERVICE_EXCEPTION = e;
    }

    public SalutThomasWSService() {
        super(__getWsdlLocation(), SALUTTHOMASWSSERVICE_QNAME);
    }

    public SalutThomasWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SALUTTHOMASWSSERVICE_QNAME, features);
    }

    public SalutThomasWSService(URL wsdlLocation) {
        super(wsdlLocation, SALUTTHOMASWSSERVICE_QNAME);
    }

    public SalutThomasWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SALUTTHOMASWSSERVICE_QNAME, features);
    }

    public SalutThomasWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SalutThomasWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SalutThomas
     */
    @WebEndpoint(name = "SalutThomasWSPort")
    public SalutThomas getSalutThomasWSPort() {
        return super.getPort(new QName("http://simple.demows.thomas.com/", "SalutThomasWSPort"), SalutThomas.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SalutThomas
     */
    @WebEndpoint(name = "SalutThomasWSPort")
    public SalutThomas getSalutThomasWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://simple.demows.thomas.com/", "SalutThomasWSPort"), SalutThomas.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SALUTTHOMASWSSERVICE_EXCEPTION!= null) {
            throw SALUTTHOMASWSSERVICE_EXCEPTION;
        }
        return SALUTTHOMASWSSERVICE_WSDL_LOCATION;
    }

}
